# Generated by Django 4.2.2 on 2023-07-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactModel',
        ),
    ]
