# Generated by Django 4.2.2 on 2023-07-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_news_slug_news_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='slug_ctg',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='slug_news',
            new_name='slug',
        ),
    ]
