# Generated by Django 4.2.2 on 2023-07-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users',
            new_name='user',
        ),
    ]
