# Generated by Django 4.2.2 on 2023-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_news_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
    ]
